config/routes.rb
Lexikographie::Application.routes.draw do
  devise_for :users

  resources :kimura_entries

  resources :wadoku_entries

  root :to => "kimura_entries#index"

end

app/models/kimura_entry.rb
#encoding: utf-8
class KimuraEntry < ActiveRecord::Base
  before_save :update_comparable_reading
  before_save :update_wordcount

  def wadoku_candidates
    WadokuEntry.where(:compare=> compare) || []
  end

  def reading_with_number
    reading + " " + number
  end

  def number
    homonyms = KimuraEntry.where(:reading => reading)
    first = homonyms.first
    "#{self.id + 1 - first.id}" 
  end
  

  belongs_to :wadoku_entry
  belongs_to :user

  private
    REPLACE = { "â" => "ā",
                "î" => "ī",
                "û" => "ū",
                "ê" => "ē",
                "ô" => "ō",
                "ä" => "ā",
                "ï" => "ī",
                "ü" => "ū",
                "ë" => "ē",
                "ö" => "ō",
                "n-a" => "n’a",
                "n-e" => "n’e",
                "n-i" => "n’i",
                "n-o" => "n’o",
                "n-u" => "n’u",
                "n-y" => "n’y",
                "-" => "·",
                #"." => "-",
                "mb" => "nb",
                "mp" => "np"
    }
  
  def make_comparable_reading
    temp = reading.dup
    REPLACE.each do |k,v|
      temp.gsub!(k,v)
    end
    temp.downcase!
    temp.gsub(/[^a-zA-Zīūēōā]/,"")
  end

  def update_comparable_reading
    self.compare = make_comparable_reading
  end

  def update_wordcount
    user = self.user
    user.wordcount += self.comment.chars.to_a.size - (self.comment_was ? self.comment_was.chars.to_a.size : 0) 
    user.save  
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :kimura_entries
end

app/models/wadoku_entry.rb
#encoding: utf-8

class WadokuEntry < ActiveRecord::Base
  before_save :update_comparable_reading
  def kanji_and_translation
    "#{kanji}: #{translation}"
  end
  has_one :kimura_entry

  private
    REPLACE = { "â" => "ā",
                "î" => "ī",
                "û" => "ū",
                "ê" => "ē",
                "ô" => "ō",
                "ä" => "ā",
                "ï" => "ī",
                "ü" => "ū",
                "ë" => "ē",
                "ö" => "ō",
                "n-a" => "n’a",
                "n-e" => "n’e",
                "n-i" => "n’i",
                "n-o" => "n’o",
                "n-u" => "n’u",
                "n-y" => "n’y",
                "-" => "·",
                #"." => "-",
                "mb" => "nb",
                "mp" => "np"
    }
  def make_comparable_reading
    temp = reading.dup
    REPLACE.each do |k,v|
      temp.gsub!(k,v)
    end
    temp.downcase!
    temp.gsub(/[^a-zA-Zīūēōā]/,"")
  end

  def update_comparable_reading
    self.compare = make_comparable_reading
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/kimura_entries_controller.rb
class KimuraEntriesController < ApplicationController
  # GET /kimura_entries
  # GET /kimura_entries.xml
  def index
    if user_signed_in? then
      @kimura_entries = current_user.kimura_entries.paginate :page => params[:page], :order => 'created_at ASC'
    else
      @kimura_entries = KimuraEntry.paginate :page => params[:page], :order => 'created_at ASC'
    end
    
    session[:back_to_index] = params[:page] || 1
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @kimura_entries }
    end
  end

  # GET /kimura_entries/1
  # GET /kimura_entries/1.xml
  def show
    @kimura_entry = KimuraEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @kimura_entry }
    end
  end

  # GET /kimura_entries/new
  # GET /kimura_entries/new.xml
  def new
    @kimura_entry = KimuraEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @kimura_entry }
    end
  end

  # GET /kimura_entries/1/edit
  def edit
    session[:back_to] = request.env["HTTP_REFERER"]
    @kimura_entry = KimuraEntry.find(params[:id])
  end

  # POST /kimura_entries
  # POST /kimura_entries.xml
  def create
    @kimura_entry = KimuraEntry.new(params[:kimura_entry])

    respond_to do |format|
      if @kimura_entry.save
        format.html { redirect_to(@kimura_entry, :notice => 'Kimura entry was successfully created.') }
        format.xml  { render :xml => @kimura_entry, :status => :created, :location => @kimura_entry }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @kimura_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /kimura_entries/1
  # PUT /kimura_entries/1.xml
  def update
    @kimura_entry = KimuraEntry.find(params[:id])

    respond_to do |format|
      if @kimura_entry.update_attributes(params[:kimura_entry])
        format.html { redirect_to(session[:back_to] || @kimura_entry, :notice => 'Kimura entry was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @kimura_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /kimura_entries/1
  # DELETE /kimura_entries/1.xml
  def destroy
    @kimura_entry = KimuraEntry.find(params[:id])
    @kimura_entry.destroy

    respond_to do |format|
      format.html { redirect_to(kimura_entries_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/wadoku_entries_controller.rb
class WadokuEntriesController < ApplicationController
  # GET /wadoku_entries
  # GET /wadoku_entries.xml
  def index

    @wadoku_entries = WadokuEntry.paginate :page => params[:page], :order => 'created_at ASC'
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @wadoku_entries }
    end
  end

  # GET /wadoku_entries/1
  # GET /wadoku_entries/1.xml
  def show
    @wadoku_entry = WadokuEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @wadoku_entry }
    end
  end

  # GET /wadoku_entries/new
  # GET /wadoku_entries/new.xml
  def new
    @wadoku_entry = WadokuEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @wadoku_entry }
    end
  end

  # GET /wadoku_entries/1/edit
  def edit
    @wadoku_entry = WadokuEntry.find(params[:id])
  end

  # POST /wadoku_entries
  # POST /wadoku_entries.xml
  def create
    @wadoku_entry = WadokuEntry.new(params[:wadoku_entry])

    respond_to do |format|
      if @wadoku_entry.save
        format.html { redirect_to(@wadoku_entry, :notice => 'Wadoku entry was successfully created.') }
        format.xml  { render :xml => @wadoku_entry, :status => :created, :location => @wadoku_entry }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @wadoku_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /wadoku_entries/1
  # PUT /wadoku_entries/1.xml
  def update
    @wadoku_entry = WadokuEntry.find(params[:id])

    respond_to do |format|
      if @wadoku_entry.update_attributes(params[:wadoku_entry])
        format.html { redirect_to(@wadoku_entry, :notice => 'Wadoku entry was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @wadoku_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /wadoku_entries/1
  # DELETE /wadoku_entries/1.xml
  def destroy
    @wadoku_entry = WadokuEntry.find(params[:id])
    @wadoku_entry.destroy

    respond_to do |format|
      format.html { redirect_to(wadoku_entries_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kimura_entries_helper.rb
module KimuraEntriesHelper
end

app/helpers/wadoku_entries_helper.rb
module WadokuEntriesHelper
end

app/views/kimura_entries/_form.html.erb
  <div class="group">
    <%= f.label :reading, t("activerecord.attributes.kimura_entry.reading", :default => "Reading"), :class => :label %>
    <%= f.text_field :reading, :class => 'text_field' %>
    <p>Eintrag-Nummer: <%=@kimura_entry.number %></p>
    <p>Generiertes Vergleichsfeld: <%=@kimura_entry.compare %></p>
    <span class="description">Die Lesung in Romaji</span>
  </div>


  

  <% if @kimura_entry.wadoku_candidates.size > 0%>
 
    <div class="group">
      <%= f.association :wadoku_entry, :collection => @kimura_entry.wadoku_candidates, :label_method => :kanji_and_translation,:value_method => :id, :as => :radio, :label_html => {:class => "label"} %> 
      <span class="description">Die ID des Wadoku_Eintrags</span>
    </div>
  <% end %>
 
  <div class="group">
    <%= f.input :comment, :label_html => {:class => "label"} %>
    <span class ="description">Ein Kommentar zu Besonderheiten des Kimura-Eintrags</span>
  </div>
  <div class="group">
    <%= f.input :kanji_comment, :label_html => {:class => "label"} %>
    <span class ="description">Ein Kommentar zu den Kanji des Kimura-Eintrags</span>
  </div>

        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>  
  <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.cancel", :default => "Cancel")}") + " " + t("web-app-theme.cancel", :default => "Cancel"), kimura_entries_path, :class => "button" %> 
</div>

app/views/kimura_entries/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/kimura_entries/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", kimura_entries_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_kimura_entry_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> KimuraEntry</h2>
    <div class="inner">
      <%= simple_form_for @kimura_entry, :url => kimura_entry_path(@kimura_entry), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/kimura_entries/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", kimura_entries_path  %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> KimuraEntries</h2>
    <div class="inner">
      <table class="table">
        <tr>             
            <th class="first">
            <%= t("activerecord.attributes.kimura_entry.reading", :default => t("activerecord.labels.reading", :default => "Reading")) %>
          </th>
          <th>Nummer</th>
          <th>Kandidaten</th>
          <th>Verknüpft mit</th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @kimura_entries.each do |kimura_entry| -%>
        <tr class="<%= cycle("odd", "even") %>">
                    <td>
            <%= link_to kimura_entry.reading, kimura_entry_path(kimura_entry) %>
          </td>
          <td><%= kimura_entry.number %></td>
          <td><%= kimura_entry.wadoku_candidates.size %></td>
          <td><%= kimura_entry.wadoku_entry ? kimura_entry.wadoku_entry.kanji : "Nichts" %></td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", kimura_entry_path(kimura_entry) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_kimura_entry_path(kimura_entry) %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
        <%= will_paginate @kimura_entries  %>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/kimura_entries/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", kimura_entries_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_kimura_entry_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  KimuraEntry</h2>
    <div class="inner">
      <%= form_for :kimura_entry, :url => kimura_entries_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/kimura_entries/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", kimura_entries_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", kimura_entry_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.kimura_entry.reading", :default => t("activerecord.labels.reading", :default => "Reading")) %>:</b>
          <%= @kimura_entry.reading %>
        </p>

        <% if @kimura_entry.wadoku_entry %>
          <p>
            <b><%= t("activerecord.attributes.kimura_entry.wadoku_entry_id", :default => t("activerecord.labels.wadoku_entry_id", :default => "Wadoku entry")) %>:</b>
            <%= @kimura_entry.wadoku_entry.kanji_and_translation %>
          </p>
        <% end %>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_kimura_entry_path(@kimura_entry), :class => "button" %> 
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kimura + Wadoku</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override", :cache => true %>
  <%= javascript_include_tag :defaults, :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><%= link_to "Kimura + Wadoku", root_url %></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <!-- <li><a href="/logout" class="logout"><%= t("web-app-theme.logout", :default => "Logout") %></a></li> -->
          <% if user_signed_in? %>
            <li>Hallo, <%= current_user.email %>!</li>
            <li>Zeichenstand: <%= current_user.wordcount%> / 10000.</li>
            <li>
              <%= link_to "Abmelden", destroy_user_session_path %>
            </li>
          <% else %>
            <li>
              <%= link_to "Anmelden", new_user_session_path %>
            </li>
          <% end %>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf"></ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> Web App.</p>
          </div>      
        </div>
      </div>
     <!-- <div id="sidebar">
        <%= yield :sidebar %>
      </div> -->
    </div>    
  </div>
</body>
</html>

app/views/wadoku_entries/_form.html.erb
<%= simple_form_for(@wadoku_entry) do |f| %>
  <% if @wadoku_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wadoku_entry.errors.count, "error") %> prohibited this wadoku_entry from being saved:</h2>

      <ul>
      <% @wadoku_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :wadoku_id %>
  </div>
  <div class="field">
    <%= f.input :kanji %>
  </div>
  <div class="field">
    <%= f.input :translation, :as => :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wadoku_entries/edit.html.erb
<h1>Editing wadoku_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @wadoku_entry %> |
<%= link_to 'Back', wadoku_entries_path %>

app/views/wadoku_entries/index.html.erb
<h1>Wadoku</h1>

<%= will_paginate @wadoku_entries%>
<table>
  <tr>
    <th>Wadoku</th>
    <th>Reading</th>
    <th>Kanji</th>
    <th>Translation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wadoku_entries.each do |wadoku_entry| %>
  <tr>
    <td><%= wadoku_entry.wadoku_id %></td>
    <td><%= wadoku_entry.reading%></td>
    <td><%= wadoku_entry.kanji %></td>
    <td><%= wadoku_entry.translation %></td>
    <td><%= link_to 'Show', wadoku_entry %></td>
    <td><%= link_to 'Edit', edit_wadoku_entry_path(wadoku_entry) %></td>
    <td><%= link_to 'Destroy', wadoku_entry, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wadoku entry', new_wadoku_entry_path %>

app/views/wadoku_entries/new.html.erb
<h1>New wadoku_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', wadoku_entries_path %>

app/views/wadoku_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Wadoku:</b>
  <%= @wadoku_entry.wadoku_id %>
</p>

<p>
  <b>Kanji:</b>
  <%= @wadoku_entry.kanji %>
</p>

<p>
  <b>Translation:</b>
  <%= @wadoku_entry.translation %>
</p>


<%= link_to 'Edit', edit_wadoku_entry_path(@wadoku_entry) %> |
<%= link_to 'Back', wadoku_entries_path %>